# Generated by Django 5.1.3 on 2024-11-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('activities', models.JSONField()),
                ('weather', models.JSONField()),
                ('diary_content', models.TextField()),
            ],
        ),
    ]
