# Generated by Django 4.2.16 on 2024-11-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0003_alter_diary_activities_alter_diary_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.TextField(blank=True, null=True),
        ),
    ]
