# Generated by Django 5.1.3 on 2024-11-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0005_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='selected_sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='similar_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='song_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='song_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='song_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
