# Generated by Django 5.1.3 on 2024-11-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0006_rename_weathers_diary_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('album', models.TextField()),
                ('lyrics', models.TextField()),
                ('original_description', models.TextField()),
                ('new_description', models.TextField()),
            ],
        ),
    ]
