# Generated by Django 5.1.3 on 2024-11-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0006_diary_selected_sentiment_diary_similar_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='song_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
