# Generated by Django 4.2.16 on 2024-11-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0007_diary_reason_alter_diary_song_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_label', models.CharField(max_length=100)),
                ('liked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaryTune.diary')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaryTune.csv_file')),
            ],
        ),
    ]
