# Generated by Django 4.2.16 on 2024-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiaryTune', '0008_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
